---
- name: Добавить k3s-костыли в конфиги LXC k3s-нод
  ansible.builtin.blockinfile:
    path: "/etc/pve/lxc/{{ item }}.conf"
    marker: "# {mark} K3S LXC TWEAKS (Ansible)"
    block: |
      lxc.apparmor.profile: unconfined
      lxc.cgroup2.devices.allow: a
      lxc.cap.drop:
      lxc.mount.auto: proc:rw sys:rw
  loop: "{{ k3s_ct_ids }}"

- name: Перезапустить k3s-ноды для применения конфигов
  ansible.builtin.command: "pct reboot {{ item }}"
  loop: "{{ k3s_ct_ids }}"
  changed_when: true

- name: Подождать загрузки контейнеров
  ansible.builtin.pause:
    seconds: 15

- name: Создать симлинк /dev/kmsg внутри нод (k3s пишет туда логи)
  ansible.builtin.command: "pct exec {{ item }} -- bash -c 'ln -sf /dev/console /dev/kmsg'"
  loop: "{{ k3s_ct_ids }}"
  changed_when: true
