[garage]
garage-s3 ansible_host=192.168.1.150 ansible_user=root

[proxmox]
homelab ansible_host=192.168.1.147 ansible_user=root

[k3s_server]
k3s-server ansible_host=10.10.1.10 ansible_user=root

[k3s_agents]
k3s-agent-1 ansible_host=10.10.2.10 ansible_user=root
k3s-agent-2 ansible_host=10.10.3.10 ansible_user=root

[k3s_cluster:children]
k3s_server
k3s_agents

[runner]
gh-runner ansible_host=10.10.1.20 ansible_user=root
