---
- name: Создать каталог конфигурации k3s
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: "0755"

- name: Прописать зеркала и локальный registry для containerd (k3s)
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/registries.yaml
    mode: "0644"
    content: |
      mirrors:
        docker.io:
          endpoint:
            - "https://dockerhub.timeweb.cloud"
        registry.k3s.io:
          endpoint:
            - "https://dockerhub.timeweb.cloud"
        "10.10.1.20:5000":
          endpoint:
            - "http://10.10.1.20:5000"
      configs:
        "10.10.1.20:5000":
          tls:
            insecure_skip_verify: true

- name: Перезапустить k3s server
  ansible.builtin.systemd:
    name: k3s
    state: restarted
  when: "'k3s_server' in group_names"

- name: Перезапустить k3s agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
  when: "'k3s_agents' in group_names"
